// GENERATED by scripts/generate-license-pubkey.py — DO NOT EDIT
enum LicensePublicKeyGenerated {
    static let kid = "dev1"
    static let publicKeyHex = "4e0fc8e9d2868cdb4000e7079621b6afa7fdaa5b34af23c59b65eafb9b05a3c4"
    static let licensePrefix = "DKLIC1"
    static let productEditionLocal = "local"
}
