/** AUTO-GENERATED by scripts/generate-room-api.py — do not edit. Source: scripts/room-api-config.json */
import Foundation

internal enum DrawsKitServerHosts {
    static let serverPathDefault = "/api/v1"
    static let recordingPathDefault = "/v1"
    static let local = "https://sdk.draw.eduskit.com"
    static let test = "https://sdk.test.drawskit.com"
    static let production = "https://sdk.draw.eduskit.com"
    static let defaultEnvironment = "production"
    static let endpointBootstrap = "bootstrap"
    static let endpointOps = "ops"
    static let endpointSyncReload = "sync-reload"
    static let endpointRecordingStart = "recording/start"
    static let endpointRecordingStop = "recording/stop"

    static func resolve(config: [String: Any]?, imTransport: Bool) -> String? {
        if let custom = config?["customServerConfig"] as? [String: Any],
           let privateHost = custom["serverHost"] as? String,
           !privateHost.isEmpty {
            return privateHost.trimmingCharacters(in: .whitespacesAndNewlines)
        }

        switch normalizeEnvironment(config?["serverEnvironment"] as? String) {
        case "local": return local
        case "test": return test
        case "production": return production
        default: break
        }

        return imTransport ? production : nil
    }

    private static func normalizeEnvironment(_ value: String?) -> String? {
        guard let value, !value.isEmpty else { return nil }
        switch value.trimmingCharacters(in: .whitespacesAndNewlines).lowercased() {
        case "local", "dev", "development": return "local"
        case "test", "staging", "preview": return "test"
        case "production", "prod", "release": return "production"
        default: return nil
        }
    }
}

