// GENERATED by scripts/generate-engine-defaults.py — DO NOT EDIT
// Source: crates/whiteboard-core/src/defaults.rs
import Foundation

/// Engine default literals generated from whiteboard-core.
enum EngineDefaultsGenerated {
    static let industryUnitMax = 100
    static let defaultStrokeColor = "#1e1e1e"
    static let defaultBrushColor = "#ff0000"
    static let defaultStrokeWidth: Float = 2
    static let defaultHighlighterColor = "#ffff00"
    static let defaultGraphColor = "#2563eb"
    static let defaultFontFamily = "sans-serif"
    static let defaultTextLineHeight: Float = 1
    static let minTextLineHeight: Float = 0.5
    static let defaultTextIndustrySize = 320
    static let textSizeToPxDivisor: Float = 20
    static let minFontSizePx: Float = 8
    static let maxFontSizePx: Float = 200
    static let textCharWidthFactor: Float = 0.55
    static let textLineHeightExtra: Float = 1.2
    static let defaultEraserSize: Float = 50
    static let defaultLaserSize: Float = 50
    static let minBrushWidthPx: Float = 0.5
    static let brushThinMaxWidth: Float = 10
    static let defaultBrushThin: Float = 30
    static let defaultGraphThin: Float = 50
    static let eraserSizeMaxRadius: Float = 12
    static let laserSizeMaxRadius: Float = 12
    static let defaultBoardScale = 100
    static let defaultScaleMin = 100
    static let defaultScaleMax = 1600
    static let defaultBoardRatio = "16:9"
    static let defaultPageWidth: Float = 1280
    static let defaultPageHeight: Float = 720
    static let lineDashDashed: [Float] = [8, 6]
    static let lineDashDotted: [Float] = [2, 4]
    static let dottedDashThreshold: Float = 3
    static let coursewareRenderModeStaticImage = "static_image"
    static let coursewareRenderModeWebview = "webview"
    static let coursewareSourceTypeImage = "image"
}
